name: AFPlecture6

library:
  source-dirs: .

dependencies: [base, containers, mtl, parsec]

default-extensions:
- BlockArguments
- FlexibleInstances
- GeneralisedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MultiParamTypeClasses
