# Packages that work on the three major OSs.
#
# See also stack-no-win.yaml.

resolver: lts-21.25

packages:
- L1
- L2
- L3
- L4
- L5
- L6
- L7
- L8
- L10
- L12
- TypeBasedModelingI
- TypeBasedModelingII
- Resumption
- assignment1/turtle-graphics-gloss
- assignment1/turtle-graphics-glut
- assignment2/replay
- assignment3/ifc/basic1
- assignment3/ifc/basic2

- live/L8
- live/L10
- live/L12

extra-deps:
- scotty-0.21
    # lts-21.25 only has scotty == 0.12, but we need >= 0.20
    # lts 22 would have a recent enough scotty
