name: turtle-graphics-glut
synopsis: A graphics library based on artistic turtles

dependencies:
- base
- OpenGL
- GLUT

library:
  source-dirs: .
  exposed-modules:
  - TurtleGraphics
  - Turtle

executables:
  coolturtle:
    source-dirs: executable
    main: Example.hs
    dependencies: turtle-graphics-glut
