name: interp

library:
  source-dirs: .

  when:
    condition: False
    exposed-modules: LiveInterpreter2025WIP

default-extensions:
- BlockArguments
- DefaultSignatures
- LambdaCase
- FlexibleContexts
- FlexibleInstances
- InstanceSigs
- MultiParamTypeClasses
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TypeOperators

dependencies:
- base >=4.12 && <5
- containers
- mtl
- parsec
