name: interp

library:
  source-dirs: .

  when:
    condition: False
    exposed-modules: LiveInterpreter2025WIP

default-extensions:
- BlockArguments
- LambdaCase
- FlexibleContexts
- FlexibleInstances
- InstanceSigs
- MultiParamTypeClasses

dependencies:
- base >=4.12 && <5
- containers
- mtl
- parsec
