name: AFPlecture5

library:
  source-dirs: .

dependencies:
- base
- foldable1-classes-compat

default-extensions:
- BlockArguments
- LambdaCase
- PatternSynonyms
- FlexibleInstances
- TypeSynonymInstances
