name: AFPlecture1

library:
  source-dirs: .

dependencies:
  - base
  - text

when:
  condition: impl(ghc >= 9.8)
  ghc-options: -Wno-x-partial

default-language: GHC2021
default-extensions:
  - BlockArguments
  - LambdaCase
  - PatternSynonyms
